services:
    n8n-worker:
        image: n8nio/n8n:latest
        restart: unless-stopped
        environment:
            - DB_TYPE=postgresdb
            - DB_POSTGRESDB_HOST=${SUPABASE_HOSTNAME}
            - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
            - DB_POSTGRESDB_USER=postgres
            - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_POSTGRESDB_DATABASE=postgres
            - N8N_DIAGNOSTICS_ENABLED=false
            - N8N_PERSONALIZATION_ENABLED=false
            - N8N_ENCRYPTION_KEY
            - N8N_USER_MANAGEMENT_JWT_SECRET
            - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
            - N8N_RUNNERS_ENABLED=true
            - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
            - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
            - EXECUTIONS_MODE=queue
            - QUEUE_BULL_REDIS_HOST=${N8N_HOSTNAME}
            - QUEUE_BULL_REDIS_PORT=6379
        command: worker
